using System.Text.Json;
using MiniPrinter.Protocol.Catalog;

namespace MiniPrinter.Protocol.Tests;

/// <summary>Compares our job bytes with jobs generated by TiMini-Print for "X5h-E07A".</summary>
public class GoldenJobTests
{
    private static readonly PrinterProfile D1 = PrinterCatalog.Default.RequireProfile("d1");

    private static string FixturePath(string file) => Path.Combine(AppContext.BaseDirectory, "Fixtures", file);

    public static TheoryData<string> Fixtures()
    {
        var data = new TheoryData<string>();
        foreach (var file in Directory.GetFiles(Path.Combine(AppContext.BaseDirectory, "Fixtures"), "*.json"))
            data.Add(Path.GetFileNameWithoutExtension(file));
        return data;
    }

    [Theory]
    [MemberData(nameof(Fixtures))]
    public void Job_bytes_match_TiMini(string name)
    {
        var fixture = Load(name);
        var pbmPath = FixturePath(name + ".pbm");

        // Image fixtures ship their exact input raster. Text fixtures do not (TiMini renders the
        // font), so their raster is recovered by decoding the expected rows.
        var page = File.Exists(pbmPath)
            ? MonoBitmap.FromPbm(File.ReadAllBytes(pbmPath))
            : ReferenceDecoder.Rows(fixture.Payload, D1.WidthPx);

        var options = new PrintOptions { Darkness = fixture.Darkness, IsText = fixture.IsText };
        var actual = new PrintJobBuilder(D1).BuildPage(page, options);

        Assert.Equal(Convert.ToHexString(fixture.Payload), Convert.ToHexString(actual));
    }

    [Fact]
    public void Image_fixture_rows_decode_to_the_input_raster()
    {
        // Guards bit order independently of our encoder: TiMini's rows must decode to the PBM.
        var expected = MonoBitmap.FromPbm(File.ReadAllBytes(FixturePath("image_pattern.pbm")));
        var decoded = ReferenceDecoder.Rows(Load("image_pattern").Payload, D1.WidthPx);
        Assert.Equal(expected.Height, decoded.Height);
        for (var y = 0; y < expected.Height; y++)
            Assert.True(expected.Row(y).SequenceEqual(decoded.Row(y)), $"row {y} differs");
    }

    [Fact]
    public void Tall_page_refreshes_speed_every_200_rows()
    {
        var frames = new FrameDecoder().Feed(Load("image_tall").Payload);
        var rowsSeen = 0;
        var refreshAt = new List<int>();
        foreach (var f in frames.Skip(4))
        {
            if (f.Command is Opcode.RleRow or Opcode.RasterRow)
                rowsSeen++;
            else if (f.Command == Opcode.Speed && f.Payload[0] == 10)
                refreshAt.Add(rowsSeen);
        }
        Assert.Equal([200, 400], refreshAt);
    }

    [Fact]
    public void Intermediate_chunk_has_no_page_end()
    {
        var page = new MonoBitmap(384, 2);
        var builder = new PrintJobBuilder(D1);
        var full = builder.BuildPage(page);
        var chunk = builder.BuildPage(page, endsPage: false);
        Assert.Equal(Convert.ToHexString(full), Convert.ToHexString([.. chunk, .. builder.BuildPageEnd()]));
    }

    private sealed record Fixture(bool IsText, int Darkness, byte[] Payload);

    private static Fixture Load(string name)
    {
        using var doc = JsonDocument.Parse(File.ReadAllText(FixturePath(name + ".json")));
        var root = doc.RootElement;
        return new Fixture(
            root.GetProperty("isText").GetBoolean(),
            root.GetProperty("darkness").GetInt32(),
            Convert.FromHexString(root.GetProperty("payloadHex").GetString()!));
    }
}

/// <summary>Independent, test-only decoder of row packets back into pixels.</summary>
internal static class ReferenceDecoder
{
    public static MonoBitmap Rows(byte[] job, int width)
    {
        var rows = new List<byte[]>();
        foreach (var f in new FrameDecoder().Feed(job))
        {
            if (f.Command == Opcode.RasterRow)
            {
                rows.Add(Enumerable.Range(0, width).Select(x => (byte)((f.Payload[x / 8] >> (x % 8)) & 1)).ToArray());
            }
            else if (f.Command == Opcode.RleRow)
            {
                var row = f.Payload.SelectMany(b => Enumerable.Repeat((byte)(b >> 7), b & 0x7F)).ToArray();
                Assert.Equal(width, row.Length);
                rows.Add(row);
            }
        }
        return new MonoBitmap(width, rows.Count, rows.SelectMany(r => r).ToArray());
    }
}
