<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>MiniPrinter.Gui</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MiniPrinter.Control\MiniPrinter.Control.csproj" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="MiniPrinter.Gui.Tests" />
    <EmbeddedResource Update="Strings.resx" Generator="" />
  </ItemGroup>
</Project>
