<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(WinTfm)</TargetFramework>
    <AssemblyName>miniprinter</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MiniPrinter.Protocol\MiniPrinter.Protocol.csproj" />
    <ProjectReference Include="..\MiniPrinter.Transport\MiniPrinter.Transport.csproj" />
    <ProjectReference Include="..\MiniPrinter.Imaging\MiniPrinter.Imaging.csproj" />
    <ProjectReference Include="..\MiniPrinter.Ipp\MiniPrinter.Ipp.csproj" />
  </ItemGroup>
</Project>
