<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.7" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MiniPrinter.Protocol\MiniPrinter.Protocol.csproj" />
    <ProjectReference Include="..\MiniPrinter.Imaging\MiniPrinter.Imaging.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="MiniPrinter.Escpos.Tests" />
  </ItemGroup>
</Project>
